In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../DATA/Ames_Without_Outliers.csv')

In [3]:
df

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2922,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2923,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,AllPub,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2924,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2925,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2926,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [4]:
# Let's drop the PID column (unnecessary index column)
df = df.drop(columns=['PID'])

In [5]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0].sort_values()

Electrical         0.034165
Garage Cars        0.034165
BsmtFin SF 1       0.034165
Garage Area        0.034165
BsmtFin SF 2       0.034165
Bsmt Unf SF        0.034165
Total Bsmt SF      0.034165
Bsmt Half Bath     0.068329
Bsmt Full Bath     0.068329
Mas Vnr Area       0.785787
Bsmt Qual          2.733174
Bsmt Cond          2.733174
BsmtFin Type 1     2.733174
BsmtFin Type 2     2.767339
Bsmt Exposure      2.835668
Garage Type        5.363854
Garage Qual        5.432183
Garage Cond        5.432183
Garage Yr Blt      5.432183
Garage Finish      5.432183
Lot Frontage      16.740690
Fireplace Qu      48.582166
Mas Vnr Type      60.642296
Fence             80.457807
Alley             93.235395
Misc Feature      96.412709
Pool QC           99.590024
dtype: float64

In [6]:
# Only one row is missing the 'Electrical' feature. Moreover, it doesn't have a default value.
# Therefore, best course of action would be to drop that row
df = df.dropna(subset='Electrical')

In [7]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage      16.746411
Alley             93.233083
Mas Vnr Type      60.628845
Mas Vnr Area       0.786056
Bsmt Qual          2.734108
Bsmt Cond          2.734108
Bsmt Exposure      2.836637
BsmtFin Type 1     2.734108
BsmtFin SF 1       0.034176
BsmtFin Type 2     2.768284
BsmtFin SF 2       0.034176
Bsmt Unf SF        0.034176
Total Bsmt SF      0.034176
Bsmt Full Bath     0.068353
Bsmt Half Bath     0.068353
Fireplace Qu      48.564593
Garage Type        5.365687
Garage Yr Blt      5.434040
Garage Finish      5.434040
Garage Cars        0.034176
Garage Area        0.034176
Garage Qual        5.434040
Garage Cond        5.434040
Pool QC           99.589884
Fence             80.451128
Misc Feature      96.411483
dtype: float64

In [8]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2922,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2923,20,RL,NaN,8885,Pave,NaN,IR1,Low,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2924,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2925,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2926,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [9]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage      16.746411
Alley             93.233083
Mas Vnr Type      60.628845
Mas Vnr Area       0.786056
Bsmt Qual          2.734108
Bsmt Cond          2.734108
Bsmt Exposure      2.836637
BsmtFin Type 1     2.734108
BsmtFin SF 1       0.034176
BsmtFin Type 2     2.768284
BsmtFin SF 2       0.034176
Bsmt Unf SF        0.034176
Total Bsmt SF      0.034176
Bsmt Full Bath     0.068353
Bsmt Half Bath     0.068353
Fireplace Qu      48.564593
Garage Type        5.365687
Garage Yr Blt      5.434040
Garage Finish      5.434040
Garage Cars        0.034176
Garage Area        0.034176
Garage Qual        5.434040
Garage Cond        5.434040
Pool QC           99.589884
Fence             80.451128
Misc Feature      96.411483
dtype: float64

In [10]:
df.columns

Index(['MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition',
       'SalePrice'],
      dtype='object')

In [11]:
# A lot of basement features are missing because some houses don't have a basement
bsmt_NA_cols = ['Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin Type 2']
bsmt_0_cols = ['BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 
               'Total Bsmt SF', 'Bsmt Full Bath', 'Bsmt Half Bath']
df[bsmt_NA_cols] = df[bsmt_NA_cols].fillna(value='NA')
df[bsmt_0_cols] = df[bsmt_0_cols].fillna(value=0)

In [12]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2922,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2923,20,RL,NaN,8885,Pave,NaN,IR1,Low,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2924,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2925,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2926,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [13]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage     16.746411
Alley            93.233083
Mas Vnr Type     60.628845
Mas Vnr Area      0.786056
Fireplace Qu     48.564593
Garage Type       5.365687
Garage Yr Blt     5.434040
Garage Finish     5.434040
Garage Cars       0.034176
Garage Area       0.034176
Garage Qual       5.434040
Garage Cond       5.434040
Pool QC          99.589884
Fence            80.451128
Misc Feature     96.411483
dtype: float64

In [14]:
# similarly for garage features
garage_NA_cols = ['Garage Type', 'Garage Finish', 'Garage Qual', 'Garage Cond']
garage_0_cols = ['Garage Cars', 'Garage Area']
df[garage_NA_cols] = df[garage_NA_cols].fillna(value='NA')
df[garage_0_cols] = df[garage_0_cols].fillna(value=0)

In [15]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0].sort_values()

Mas Vnr Area      0.786056
Garage Yr Blt     5.434040
Lot Frontage     16.746411
Fireplace Qu     48.564593
Mas Vnr Type     60.628845
Fence            80.451128
Alley            93.233083
Misc Feature     96.411483
Pool QC          99.589884
dtype: float64

In [16]:
# Let's deal with Mas Vnr now, in a similar fashion
df['Mas Vnr Type'] = df['Mas Vnr Type'].fillna('NA')
df['Mas Vnr Area'] = df['Mas Vnr Area'].fillna(0)

In [17]:
# For Fence, Alley, Misc Feature and Pool QC, we could fill it in with 'NA' values
# Since these are categorical columns, we will have to think about converting them later
# To save us all that hassle, let's just drop them
df = df.drop(columns=['Fence', 'Alley', 'Misc Feature', 'Pool QC'])

In [18]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage     16.746411
Fireplace Qu     48.564593
Garage Yr Blt     5.434040
dtype: float64

In [19]:
# All the records missing 'Fireplace Qu' don't have a fireplace
df[df['Fireplace Qu'].isna()]['Fireplaces'].value_counts()

Fireplaces
0    1421
Name: count, dtype: int64

In [20]:
df['Fireplace Qu'] = df['Fireplace Qu'].fillna(value='NA')

In [21]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage     16.746411
Garage Yr Blt     5.434040
dtype: float64

In [22]:
# Fill in lot frontage based on the description and domain knowledge
# Solution: Fill in missing values with mean per neighbourhood
df['Lot Frontage'] = df.groupby('Neighborhood')['Lot Frontage'].transform(lambda value: value.fillna(value.mean()))

In [23]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Lot Frontage     0.102529
Garage Yr Blt    5.434040
dtype: float64

In [24]:
# Some neighbourhoods don't have a lot frontage at all
# Solution: Fill in with 0
df['Lot Frontage'] = df['Lot Frontage'].fillna(0)

In [25]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Garage Yr Blt    5.43404
dtype: float64

In [26]:
# For garage year built, I'm going to check how many years after the house was it built on average
# Take mean per neighbourhood and fill it in
df['Garage delay'] = df['Garage Yr Blt'] - df['Year Built']

In [27]:
df['Garage delay'] = df.groupby('Neighborhood')['Garage delay'].transform(lambda value: value.fillna(value.mean()))

In [28]:
df['Garage Yr Blt'] = df['Year Built'] + df['Garage delay']

In [29]:
df = df.drop(columns='Garage delay')

In [30]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.000000,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,20,RH,80.000000,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,20,RL,81.000000,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,20,RL,93.000000,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,60,RL,74.000000,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2922,80,RL,37.000000,7937,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,...,0,0,0,0,0,3,2006,WD,Normal,142500
2923,20,RL,75.144444,8885,Pave,IR1,Low,AllPub,Inside,Mod,...,0,0,0,0,0,6,2006,WD,Normal,131000
2924,85,RL,62.000000,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,700,7,2006,WD,Normal,132000
2925,20,RL,77.000000,10010,Pave,Reg,Lvl,AllPub,Inside,Mod,...,0,0,0,0,0,4,2006,WD,Normal,170000
2926,60,RL,74.000000,9627,Pave,Reg,Lvl,AllPub,Inside,Mod,...,0,0,0,0,0,11,2006,WD,Normal,188000

In [31]:
percent_missing = 100 * df.isna().sum() / df.shape[0]
percent_missing[percent_missing > 0]

Series([], dtype: float64)

In [32]:
# No more missing data! Yay!
# Now save it before it's too late

In [33]:
df.to_csv('../DATA/Ames_Without_Missing.csv', index=False)